### ISSUE TITLE
Statisch getypeerde CSS classes

### ISSUE THREAD

**Issue by MaartjeArnoldus** [progressonderwijs/ProgressOnderwijsUtils#729]
Progress maakt gebruik van DSL om html te genereren via C#. CSS classes worden nu door middel van een string meegegeven aan html elementen. Deze string wordt niet gevalideerd en kan verkeerd zijn.
**Wat te doen?**

- [x] Maak van elke CSS class een C# object;
- [x] #742
- [x] Valideer de set van CSS classes in C# ten opzichte van die in de CSS files;
- [x] Verander de manier waarop de CSS class meegegeven wordt aan html elementen zodat geen willekeurige strings meer meegegeven kunnen worden.

**Moeilijkheid**

- [x] String concateneren van niet constante variabelen (zoals database waardes);
- [x] Meerdere classes meegeven aan een html element.
- [x] De HTML DSL zit in een andere assembly dan progress, dus er zal een abstractie-laag moeten komen om de set aan CSS-C#-constantes uit progress te kunnen koppelen met de HTML library.

**Nawerk/Issues**
- [ ] #747

(bron: https://docs.google.com/document/d/1oPb4FQMKIEY7BxGch_G3d8tJpQynGnmI)

**Comment by MaartjeArnoldus** [comment]
u-largePaddingTop en u_largePaddingBottom zijn geen bestaande classes (zijn niet in de css/ js files te vinden) 

link: https://github.com/progressonderwijs/progress/blob/maartje/staticly-typed-css-classes/src/Progress.WebApp/Catalogue/CatalogueOnderwijsController.cs#L76

**Comment by EamonNerbonne** [comment]
rare classes vinden: dat is nou juist (en van de) punten van deze exercitie - mooi!

**Comment by MaartjeArnoldus** [comment]
Volgens mij returned deze methode altijd een default string als cssClass. moet dit nog behouden worden?

https://github.com/progressonderwijs/progress/blob/maartje/staticly-typed-css-classes/src/Progress.Business/Volg/Definitie/OnderwijsKaart.cs#L60-L64

**Comment by EamonNerbonne** [comment]
Lijkt me idd totaal niet nodig.

In dit soort gevallen (waar je het vrij waarschijnlijk acht dat de code aangepast moet worden met idee van hoe) is het meestal redelijk om een draft-PR te maken met je voorstel, dan is er ook direct een diff om over te praten en meestal is er iets om te mergen.

**Comment by MaartjeArnoldus** [comment]
#734
