### ISSUE TITLE
Maak een Css parser voor het verkrijgen van alle css classes;

### ISSUE THREAD

**Issue by MaartjeArnoldus** [progressonderwijs/ProgressOnderwijsUtils#742]
Om de c# Styleclass files te genereren is er een css parser nodig om de css classes te verkrijgen.
- [x] Verwijderen van alle comments uit een CSS file;
- [x] Verwijderen van alle strings uit een CSS file;
- [x] #744
- [x] Extra checks om de CSS classes te valideren (zie #744); 
- [x] #749
- [x] #751
- [x] #754
- [x] Voor het implementatie: de bestaande objectnamen renamen naar de nieuwe naamgeving.

**Comment by MaartjeArnoldus** [comment]
@Bazeloth heb jij toevallig nog een mening over de naamgeving van de StyleClass Objecten?
Op dit moment wordt daar alles met een hoofdletter geschreven en worden enkele en dubbele '-'/'_' vervangen door een '_'.
Dit zou natuurlijk nog veranderd kunnen worden. Alleen worden '-' niet geaccepteerd.

**Comment by Bazeloth** [comment]
Niet perse. Enige wat nu wel vervelend is dat ik niet een class zoals u-linkStyling kan opzoeken als CssClass; dit is namelijk U_LinkStyling. We hebben nog geen harde afspraken over naamgeving dus misschien wordt het eens tijd daar aan te denken zodat dit soort issues minder voorkomen.

Ook hebben we classes die als component dienen zoals:
![image](https://user-images.githubusercontent.com/19928782/192275495-f348e008-7b03-4233-b0ca-794f3af9263d.png)

Dit heette eerst ReleaseNote**s**-foo (met dus een extra iets). Dit hernoemen is een peulenschil in een .css file, maar elk onderdeel van ReleaseNote zoals ReleaseNote_Field moet ik hernoemen met ReSharper. Dit werkt moeizaam.

Ter info cc @EamonNerbonne .

**Comment by EamonNerbonne** [comment]
wmb is de upper/lowercasing niet nodig; als we dat belangrijk vinden, kunnen we dat ook wel in de CSS aanpassen.  Echter kan dat ook prima op een later moment; heeft geen haast.

We waren van plan tot nu toe om https://github.com/suitcss/suit/blob/master/doc/naming-conventions.md te volgen, maar het is wmb ook het overwegen waard om SUIT, maar met `_` ipv `-` te doen en zo de C# field name _exact_ gelijk aan de CSS class name te kunnen houden, lekker makkelijk.  Maar ook dat kan prima later, en zou wel een hele find-replace tour zijn.  Lijkt je dat een goed idee @Bazeloth ?

**Comment by Bazeloth** [comment]
Jawel, maar hoe ga je dat met modifiers doen?

![image](https://user-images.githubusercontent.com/19928782/192302358-55b9ea1d-8236-46d0-885d-165975672952.png)

**Comment by EamonNerbonne** [comment]
yep, lijkt me wel?

**Comment by MaartjeArnoldus** [comment]
Dus de standaard benaming in de CSS alleen de - vervangen door _?

**Comment by Bazeloth** [comment]
Lijkt me wel idd. Ik vind `-` een stuk prettiger lezen, maar ik denk dat we geen keuze hebben. u-linkStyling wordt dan u_linkStyling. We kunnen ook U_LinkStyling doen in de css. Mn voorkeur gaat echter uit naar u_linkStyling.

**Comment by fdij** [comment]
Waarom ben ik hier aan assigend? Ik haal mij voor nu er maar vanaf.

**Comment by Bazeloth** [comment]
> Waarom ben ik hier aan assigend? Ik haal mij voor nu er maar vanaf.

Ik neem aan omdat dit elke programmeur aan gaat, maar de communicatie van de werking kan ook prima achteraf.
