### ISSUE TITLE
Alle woorden verkrijgen die beginnen met een punt uit een CSS file;

### ISSUE THREAD

**Issue by MaartjeArnoldus** [progressonderwijs/ProgressOnderwijsUtils#744]
**Volgorde van het parsen:**
- Comments verwijderen;
- Strings verwijderen;
- Alle woorden die met een punt beginnen ophalen.

**Hoe complex wordt de regex of ga je de css ook valideren?**
- Begint niet met een nummer (een class heeft dit nooit en dimensions enz wel);
-  '-' mag geen class zijn;
- '-digit' is niet toegestaan aan het begin;
- '\\' is toegestaan voor een hex digit alleen willen we dit ondersteunen?

[Zie link (CSS tokens)](https://www.w3.org/TR/css-syntax-3/#ident-token-diagram)

**Comment by EamonNerbonne** [comment]
> * '\' is toegestaan voor een hex digit alleen willen we dit ondersteunen?

Ik stem voor detecteren en crashen als eerste versie.

**Comment by EamonNerbonne** [comment]
Oh, en for posterity: geen gebruik gemaakt van AngleSharp.Css, want de tokenizer API is private, en de public API exposed niet alle classnames in gevallen waar anglesharp de semantiek van de css nog niet goed ondersteund.

**Comment by MaartjeArnoldus** [comment]
objectname format veranderd
