### ISSUE TITLE
Opstellen van een StyleClasses bestand;

### ISSUE THREAD

**Issue by MaartjeArnoldus** [progressonderwijs/ProgressOnderwijsUtils#749]
Is er voorkeur voor een volgorde of groepering?
Denk bijvoorbeeld aan:
- Alfabetisch;
- Volgorde van occurrence;
- Per (CSS) file gegroepeerd;

**Comment by Bazeloth** [comment]
Per (CSS) file gegroepeerd;

**Comment by MaartjeArnoldus** [comment]
Ik neem aan dat er dan een StyleClass file per CSS file moet komen als dat het geval is.

**Comment by EamonNerbonne** [comment]
Sure, maar er zijn maar een handje vol - en die wil je denk ik wel handmatig configureren, dus netto komt het dan bijv. op een aantal aanroepen van whatever util of helper jij maakt aan: een param voor de css file pad, en een param voor de beoogde C# output pad, en evt. nog een paar params voor zaken als namespaces enzo.
