### ISSUE TITLE
Uitlezen van de juiste CSS files;

### ISSUE THREAD

**Issue by MaartjeArnoldus** [progressonderwijs/ProgressOnderwijsUtils#751]

**Comment by EamonNerbonne** [comment]
Dus zoals IRL besproken is het mogelijk verstandig om iig in eerste instantie alle business css (output) files in een C# file te representeren zodat de overgang naar de automatisch gegenereerde file soepeler kan; het splitsen per file is immers best nog wat additionele complexiteit.

(Maar we hebben ook besproken hoe je via reflectie en regexes idd over de bestaande BusinessStyleClasses zou kunnen itereren en de code toch gestructureerd fixen)
