### ISSUE TITLE
Ts cssClasses generator + scanner

### ISSUE THREAD

**Issue by MaartjeArnoldus** [progressonderwijs/ProgressOnderwijsUtils#788]
zie https://github.com/progressonderwijs/ProgressOnderwijsUtils/issues/747#issuecomment-1331945421.

Maak een ts gen voor de cssClasses (enum)
Maak een simpele scanner die de usages van de classes vind in de ts
generate de BussinessJs method 
``` C#
UsedImplicitlyByJs()
```
om alle gebruikte classes in de ts een usage te geven

classes defineren in de css met een empty block

**Comment by EamonNerbonne** [comment]
done
